VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsOrdine"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Security As String
Public ISIN As String
Public Crncy As String
Public Price As Double
Public Bank As String
Public Client As String
Public Portfolio As String
Public Number As Double
Public Amount As String
Public Pct As Double
Public AssetClass As String
Public SubClass As String
Public OrderType As String
